"""empty message

Revision ID: 72ed1a5344f2
Revises: 
Create Date: 2023-04-20 19:46:49.942536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ed1a5344f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('expense_id', sa.Integer(), nullable=False),
    sa.Column('expense_name', sa.String(length=100), nullable=True),
    sa.Column('expense_amount', sa.Float(), nullable=True),
    sa.Column('expense_type', sa.String(length=100), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('expense_id')
    )
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('goal_amount', sa.Float(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goals')
    op.drop_table('expenses')
    op.drop_table('users')
    # ### end Alembic commands ###
